name: dms_mermaid
channels:
  - cadwr-dms
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pyproj
  - nodejs
  - sphinx
  - sphinx_rtd_theme
  - sphinx
  - sphinx-design
  - sphinx-argparse  
  - sphinxcontrib-bibtex
  - sphinxcontrib-mermaid
  - sphinx_rtd_theme
  - nbsphinx
  - pillow>=4.0.0

# For VSCode you'll want to install extension: Markdown Chart by markdownchart.com

# npm config set registry http://registry.npmjs.org/
# npm config set strict-ssl false
# npm install -g @mermaid-js/mermaid-cli

# use like: mmdc -i input.mmd -o output.svg
# see documentation: https://github.com/mermaid-js/mermaid-cli