---
config:
  look: classic
  theme: base
---
%%{
    init: {
        'theme': 'base',
        'themeVariables': {
        'primaryColor': '#fff',
        'primaryTextColor': '#000',
        'primaryBorderColor': '#002570',
        'lineColor': '#000',
        'secondaryColor': '#d1d1d1',
        'tertiaryColor': '#fff'
        }
    }
}%%

flowchart TD
    
    %% Gridding -------------------------------------------------------------------------
    subgraph mesh [<span style='display: inline-flex; align-items: center; color:white'><img src='https://api.iconify.design/mdi:cursor-default-click-outline.svg?color=white' width='20' height='20' style='margin-right: 4px;' /> Gridding</span>]
    end
    %% Style
    style mesh fill:#75590d, stroke:#1a0f13, color:#FFFFFF
    click mesh "https://cadwrdeltamodeling.github.io/BayDeltaSCHISM/topics/mesh.html" _blank

    %% Time Series Inputs -------------------------------------------------------------------------
    subgraph bd [Time Series Inputs]
        time_ins(<span style='display: inline-flex; align-items: center;'><img src='https://api.iconify.design/mdi:cursor-default-click-outline.svg' width='20' height='20' /> Inflow Boundaries</span>)
        ocean_in(<span style='display: inline-flex; align-items: center;'><img src='https://api.iconify.design/mdi:cursor-default-click-outline.svg' width='20' height='20' style='margin-right: 4px;' /> Ocean Boundary</span>)
        atmos_in(<span style='display: inline-flex; align-items: center;'><img src='https://api.iconify.design/mdi:cursor-default-click-outline.svg' width='20' height='20' style='margin-right: 4px;' /> Atmospheric Forcings</span>)
    end
    %% Style
    style bd fill:#c8bce0, stroke:#3e3254, color:#FFFFFF
    style time_ins fill:#e9e1f7, stroke:None
    style ocean_in fill:#e9e1f7, stroke:None
    style atmos_in fill:#e9e1f7, stroke:None
    click time_ins "https://cadwrdeltamodeling.github.io/BayDeltaSCHISM/topics/flow_boundary.html" _blank
    click ocean_in "https://cadwrdeltamodeling.github.io/BayDeltaSCHISM/topics/ocean.html" _blank
    click atmos_in "https://cadwrdeltamodeling.github.io/BayDeltaSCHISM/topics/atmospheric.html" _blank

    %% Spatial Inputs -------------------------------------------------------------------------
    subgraph si [Spatial Inputs]
        nudge(<span style='display: inline-flex; align-items: center;'><img src='https://api.iconify.design/mdi:cursor-default-click-outline.svg' width='20' height='20' /> Nudging</span>)
        hotstart(<span style='display: inline-flex; align-items: center;'><img src='https://api.iconify.design/mdi:cursor-default-click-outline.svg' width='20' height='20' style='margin-right: 4px;' /> Hotstart</span>)
        veg(<span style='display: inline-flex; align-items: center;'><img src='https://api.iconify.design/mdi:cursor-default-click-outline.svg' width='20' height='20' style='margin-right: 4px;' /> Vegetation</span>)
    end
    %% Style
    style si fill:#e3cbb1, stroke:#473a2c, color:#FFFFFF
    style nudge fill:#f2e7da, stroke:None
    style hotstart fill:#f2e7da, stroke:None
    style veg fill:#f2e7da, stroke:None
    click nudge "https://cadwrdeltamodeling.github.io/BayDeltaSCHISM/topics/nudging.html" _blank
    click hotstart "https://cadwrdeltamodeling.github.io/BayDeltaSCHISM/topics/hotstart.html" _blank
    click veg "https://cadwrdeltamodeling.github.io/BayDeltaSCHISM/topics/vegetation.html" _blank


    %% SCHISM -------------------------------------------------------------------------
    schism{SCHISM Simulation}
    style schism fill:#7fa6b3, stroke:None, color:#FFFFFF


    %% Connections -------------------------------------------------------------------------
    mesh --> si
    bd --> schism
    si --> schism
    
%% dms_mermaid\diagrams> mmdc -i .\bds_general_map.mmd -o ../docsrc/svg/bdschism_general.svg